### ISSUE TITLE
[!] A self-corrected current version for Capybara tutorial & ARCHS4 Mining for human reference

### ISSUE THREAD

**Issue by Danyi-ZHENG** [morris-lab/Capybara#11]
Hi! I am here to share a self-corrected current version for the Capybara tutorial & ARCHS4 Mining.

The corrected new script is uploaded at the link below.

Feel free to let me know if there is any error, this is just a self-corrected version, and the original author of Capybara has no responsibility.

Once again, thank you so much for this amazing package!
    
    
[https://github.com/Danyi-ZHENG/Capybara_self_corrected_tutorials](url)

**Comment by Danyi-ZHENG** [comment]
The ARCHS4 mining is for creating a human bulk reference!

**Comment by KaetheKong** [comment]
Thanks for the update!
