### ISSUE TITLE
Can I use the sum of empirical p-value of other lineages to represent the hybrid score?

### ISSUE THREAD

**Issue by GilbertHan1011** [morris-lab/Capybara#12]
Hello, sorry to bother you again.

I have a muti-lineage dataset. I find that there are groups of immature cells are identified to be a specific cell type (_celltype1_) with no hybrid cells. This group of cells have too little expression of other lineage-specific-gene to be identify to be hybrid cells. However, I think it's important to explain this immaturity. I find the difference between this immature cells and mature cells are the low empirical p-value of other lineage(**perc.list** in the [toturial](https://github.com/morris-lab/Capybara/blob/master/README.md). I  sum the logarithm of 
 **perc.list** to represent the hybird score and find the results turn out to be excellent. But I don't know whether the results can proof my opinoin. Here are my code. 
```R
background.mtx <- read.csv("../4.7_osteo_ident_score/process/4.7_run5_stem_ref_scClassifier_reference_mix90_normalize_select_scale.csv", header = T, row.names = 1, stringsAsFactors = F)
mtx.test <- read.csv("../4.7_osteo_ident_score/process/4.7_run5_stem_query_scClassifier_reference_mix90_test_normalize_select_scale.csv", header = T, row.names = 1, stringsAsFactors = F)
col.sub <- ncol(background.mtx) - 2
ref.perc.list <- percentage.calc(background.mtx[,c(1:col.sub)], background.mtx[,c(1:col.sub)])
perc.list <- percentage.calc(as.matrix(mtx.test[,c(1:col.sub)]), as.matrix(background.mtx[,c(1:col.sub)]))
scoreFun2 <- function(x){
  mean((-log(x[[1]]$frxn_cell.type_ChondroLineage))+(-log(x[[1]]$frxn_cell.type_Derm))+(-log(x[[1]]$frxn_cell.type_Meninges))+
         (-log(x[[1]]$frxn_cell.type_Periosteum))+(-log(x[[1]]$frxn_cell.type_Smooth.muscle))+(-log(x[[1]]$frxn_cell.type_Stem.cell)))
}
identScore2 <- sapply(perc.list,scoreFun2)
```
I'd be more than grateful if you can have a look of this code.

**Comment by KaetheKong** [comment]
Hi Gilbert,

No worries at all! Happy to help!

The hybrid detection in the pipeline requires the distributions of empirical p-values of the two cell types to be from the same distribution. Therefore, little differences can still be considered different with significant p-values based on Mann Whitney rank-sum test.

I think your approach makes sense. If I understand this correctly, the hybrid score for the immature cells would be high as the empirical p-values are low across the cell types, explaining that these cells are mapping to multiple lineages. The only potential concern would be if there is one cell type that has dominantly low p-values, driving the score to be high. In that case, the score would be similar to the hybrid scores of the mature cell types and maybe consider filter them out.

Hope this helps! Thanks for the feedback!
Wenjun

**Comment by GilbertHan1011** [comment]
Thanks! It's really a great help!
