### ISSUE TITLE
count.csv generation

### ISSUE THREAD

**Issue by rigitano** [morris-lab/Capybara#5]
Hello,

I'm having a hard time understanding how the count.csv files were generated from the MCA files from https://figshare.com/articles/MCA_DGE_Data/5435866 . (step 1.5 on GitHub). Due to the large size, these files were not provided.

I didn't succeed in generating the count.csv files from the MCA files. Could I ask for your help on indicating how this was done? (Maybe one count.csv example could be enough to clarify the procedure)

Thank You

**Comment by Danyi-ZHENG** [comment]
it should be the 500dge/batch_rm_dge folders in the MCA link provided at the top of the webpage.

**Comment by rigitano** [comment]
Hi, 

In the MCA link provided at the top of the webpage (https://figshare.com/articles/MCA_DGE_Data/5435866) I could only find folders with similar, but different names:

MCA_500more_dge.tar.gz\500more_dge
MCA_BatchRemove_dge.zip\rmbatch_dge

However, instead of a "cont.csv" file, they contain several ".txt" files. I've checked the older versions, but couldn't find any count.csv files either.

This rises two questions:
1- Which one of the those folders is the right one?
2- How do I transform their .txt content in a count.csv file?

Thank you for your help

**Comment by Danyi-ZHENG** [comment]
I tried both, and I think the rmbatch one works. Actually you don't have to change txt to csv, just change the read.csv function to read.table function and make sure the loop goes through the whole folder. You don;t have to creat exactly the same file format as they provide.

**Comment by KaetheKong** [comment]
Hi,

First of all, apologies for the delay! And thank you for using Capybara!

Thanks for helping in responding in this thread! The files "count.csv" were coming from one of the older versions, generated to contain only the genes that are shared across all different cell types. I believe the MCA has been updated in the recent years and please use the newer count files. To generate these count files, I would recommend using the rmbatch ones and stitching different replicates together by joining with the shared genes. 

As suggested above, it is not necessary for it to be the same format. Please use read.csv for comma delimited files and read.table for tab delimited files. Please let us know if you have issues reading these files!

Best,
Wenjun

**Comment by rigitano** [comment]
Thanks a lot for the support and for the package itself!

Just to see if I understood everything correctly: 

1- A possible solution would be to create one folder for each tissue, putting inside each one the corresponding .txt files
2- In the tissues with several corresponding .txt files (e.g. BoneMarrow1_rm.batch_dge.txt, BoneMarrow2_rm.batch_dge.txt, BoneMarrow3_rm.batch_dge.txt) it's necessary to unify all the files in one, using pd.concat for example. From what I understood, leaving several files for each tissue might lead to problems downstream.

Oh... and one last thing: the older versions are still on the MCA website. As a first test run of my code, I would like to use the same database that you did. Which version did you use?

Thanks again
