### ISSUE TITLE
##Step 2: Generation of a High-Resolution Custom Reference, and Continuous Identity Measurement #Get the counts of the cell types involved in the tissues selected

### ISSUE THREAD

**Issue by Danyi-ZHENG** [morris-lab/Capybara#6]
`pancreatic.all.meta <- mca.meta[which(mca.meta$tissue %in% final.cell.types.adult), ]

mca.counts.all.involved <- NULL
tissues.to.read <- unique(pancreatic.all.meta$tissue)
general.path <- "~/Stroke/Capybara_Cell_Stem_cell/MCA_data/500more_dge/"
for (i in 1:length(tissues.to.read)) {
  curr.t <- tissues.to.read[i]
  curr.path.to.read <- paste0(general.path, curr.t, "_dge.txt")
  curr.count <- read.table(curr.path.to.read)#, header = T, row.names = 0, stringsAsFactors = F)#, header = T, row.names = 1, stringsAsFactors = F)
  if (is.null(mca.counts.all.involved)) {
    mca.counts.all.involved <- curr.count
  } else {
    mca.counts.all.involved <- cbind(mca.counts.all.involved, curr.count)
  }
}`

Error message: 
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 20283, 18878

I am using the 500dge folders as MCA counts, and when it selects pancreas and stomach as demonstrated, it bumped out this error, and I fail to fix this bug. I think it's because the pancreas has 20283 genes and the stomach has 18878 genes in the txt files, so the two dataframe cannot merge/rbind/cbind. Can you help have a look?

**Comment by KaetheKong** [comment]
Hello,

Apologies for the delayed response! Thank you for using Capybara!

I would recommend joining using the shared genes. Instead of `mca.counts.all.involved <- cbind(mca.counts.all.involved, curr.count)`, you could replace with following lines of code: 

`gene.shared <- intersect(rownames(mca.counts.all.involved), rownames(curr.count))`
`mca.counts.all.involved <- cbind(mca.counts.all.involved[gene.shared,], curr.count[gene.shared,)`

An alternative approach is to use the union of genes and add zeros to genes that are not present in the other count file. Yet, this is not recommended as it adds leading zeros to the matrices, which could cause matrix computation errors in the downstream analysis.

Hope this is helpful!
Let us know if this works out!
Best,
Wenjun

**Comment by Danyi-ZHENG** [comment]
Hi!
I spent two weeks dealing with the whole script and found out a few mistakes throughout all these version evolutions. I finally successfully ran through the whole script and generate the plots. I am willing to share my script if needed. Pls let me know how to if so.
Thank you so much for creating this amazing package! Really useful to our lab!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: KaetheKong ***@***.***>
发送时间: Tuesday, April 12, 2022 12:36:09 AM
收件人: morris-lab/Capybara ***@***.***>
抄送: Zheng Danyi ***@***.***>; Author ***@***.***>
主题: Re: [morris-lab/Capybara] ##Step 2: Generation of a High-Resolution Custom Reference, and Continuous Identity Measurement #Get the counts of the cell types involved in the tissues selected (Issue #6)

        - External Email -



Hello,

Apologies for the delayed response! Thank you for using Capybara!

I would recommend joining using the shared genes. Instead of mca.counts.all.involved <- cbind(mca.counts.all.involved, curr.count), you could replace with following lines of code:

gene.shared <- intersect(rownames(mca.counts.all.involved), rownames(curr.count))
mca.counts.all.involved <- cbind(mca.counts.all.involved[gene.shared,], curr.count[gene.shared,)

An alternative approach is to use the union of genes and add zeros to genes that are not present in the other count file. Yet, this is not recommended as it adds leading zeros to the matrices, which could cause matrix computation errors in the downstream analysis.

Hope this is helpful!
Let us know if this works out!
Best,
Wenjun

―

**Comment by rigitano** [comment]
Hi, I would like to see your corrected script, please. 

My email: henrique.rigitano@gmail.com

Thank you!

**Comment by Danyi-ZHENG** [comment]
> Hi, I would like to see your corrected script, please.
> 
> My email: [henrique.rigitano@gmail.com](mailto:henrique.rigitano@gmail.com)
> 
> Thank you!

Hi! I've open a new issue and the script is available there. Thank you!

**Comment by Danyi-ZHENG** [comment]
Hi!
I shared the link in the new issue I opened just now. Thank you!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: rigitano ***@***.***>
发送时间: Thursday, April 14, 2022 12:28:09 AM
收件人: morris-lab/Capybara ***@***.***>
抄送: Zheng Danyi ***@***.***>; Author ***@***.***>
主题: Re: [morris-lab/Capybara] ##Step 2: Generation of a High-Resolution Custom Reference, and Continuous Identity Measurement #Get the counts of the cell types involved in the tissues selected (Issue #6)

        - External Email -



Hi, I would like to see your corrected script, please.

My email: ***@***.******@***.***>

Thank you!

―
