### ISSUE TITLE
Use terminally differentiated cells as reference

### ISSUE THREAD

**Issue by GilbertHan1011** [morris-lab/Capybara#8]
Hello, I have a single cell dataset about differentiation from stem cells to mulitple lineage cells. I can't find ideal cell type in Mouse Cell Alta, however. I'd like to ask if I can use the terminal differentiated cells in my own dataset if I'm sure the the destination of stem cells to predict the cell identity of stem cell. 
I'd be more than happy if you answered my question!

**Comment by KaetheKong** [comment]
Hello,

First of all, thank you for using Capybara! And apologies for the delayed response!

Yes, if you have known terminally differentiated cells in your own dataset, you could skip the steps from MCA directly to build the high-resolution reference. The inputs would be the single-cell matrix for these cells in your dataset with a metadata table labeling their identity (such as term1, term2, etc). With these inputs, you would be able to get the reference established and run through the remaining of the pipeline.

Hope this is helpful! Let us know if this works out!

Best,
Wenjun

**Comment by GilbertHan1011** [comment]
Thanks!

**Comment by GilbertHan1011** [comment]
Thanks! It's really helpful!

I tried this method in my own dataset and it works in most situations. I cross verified the result with other methods like scPred and the result was excellent. Howerver, when the dataset have multiple lineages, and some of the lineages are in terminal states, while others are not so mature, Capybara will classify most of the stem cells' identity to the lineages whose reference cells are not so terminal. For example, mouse embryos at E14 have developed the mature chondrocytes, but periosteal cells remain unmature state. When I apply Capybara to build the reference with chondrocytes and periosteal cells to predict stem cells identity, most of the stem cells are classified to periosteal cells, which is unsatisfactory. When I use scPred, most of these cells are labeled unassigned. I don't know whether I can solve this situation with Capybara. 

I really love Capybara and I hope that my feedback can bring some improvement!

Gilbert

**Comment by KaetheKong** [comment]
Hi Gilbert,

Thanks a bunch for the feedback! I am assuming that you are following the pancreas example in this repository. I would recommend looking through the notebooks (Figure 2-3 would be a good reference) in this [repository](https://github.com/morris-lab/Capybara_reproducibility). 

In the updated version, we included an additional initial classification step in the pipeline, distinguishing the unknowns from the single/hybrid cell identities. This might be helpful in the separation of these cells. This step is not automated in one function yet as it requires some parameter selection and we are working on better separating the different distributions.

Let us know if that helps with the performance!
Best,
Wenjun

**Comment by GilbertHan1011** [comment]
Thank you, Wenjun.

I didn't notice this repository before. I'll try this methods right away and let you know if I have more questions.

Thanks again for you generous help!

Gilbert

**Comment by KaetheKong** [comment]
Sure thing! I will close this issue for now. Feel free to open new ones if you have any further questions!
