### ISSUE TITLE
[!] A self-corrected current version for Capybara tutorial

### ISSUE THREAD

**Issue by Danyi-ZHENG** [morris-lab/Capybara#9]
Hi! I spent two weeks going through the whole tutorial, and corrected errors to fit the current available MCA and else. The corrected new script is uploaded at the link below. Feel free to let me know if there is any error, this is just a self-corrected version, and the original author of Capybara has no responsibility. Once again, thank you so much for this amazing package!
[https://github.com/Danyi-ZHENG/Capybara_MCA_tutorial](url)

**Comment by KaetheKong** [comment]
Hello,

Thank you so much for sharing this! Apologies for answering these questions late. And glad it worked finally with the current available MCA and others! I will edit the tutorial accordingly for the newer versions of the MCA.

Thanks again!
Wenjun
